base_url = "https://wouterjehee.com"
title = "Wouter Jehee"

compile_sass = false

feed_filename = "rss.xml"
build_search_index = false

external_links_target_blank = true

taxonomies = [
    {name = "series", feed = true, paginate_by = 10},
]

[markdown]
highlight_code = true

[extra]
icon_size = 42

