base_url = "https://wouterjehee.com"
title = "Wouter Jehee"

compile_sass = false

generate_feeds = true
feed_filenames = [ "rss.xml" ]

build_search_index = false

taxonomies = [
    {name = "series", feed = true, paginate_by = 10},
]

[markdown]
highlight_code = true
external_links_target_blank = true

[extra]
icon_size = 42

