baseURL = "https://wouterjehee.com"
languageCode = "en-us"
title = "Wouter Jehee"
theme = "hermit"

copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

pygmentsCodefences  = true
pygmentsUseClasses  = true
enableEmoji = true
rssLimit = 10

[author]
  name = "Wouter Jehee"

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  themeColor = "#d8dee9"

  homeSubtitle = "CSE Student | Developer"
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  bgImg = "1.jpg"

  justifyContent = false
  relatedPosts = false
  code_copy_button = true
  
  # customCSS = ["css/foo.css", "css/bar.css"]

  [[params.social]]
    name = "email"
    url = "mailto:wouterjehee@tutanota.com"

  [[params.social]]
    name = "github"
    url = "https://github.com/wjehee"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10
